spring:
  datasource:
      url: jdbc:mysql://47.106.67.30:3306/jk?serverTimezone=GMT%2B8
      username: root
      password: 18774954780jkl

server:
  port: 8899

jk:
  cfg:
    cors-origins:
      - https://www.mj666.com
  upload:
    base-path: /ASM/code/jk/
    upload-path: upload/
    image-path: img/
    video-path: video/