spring:
  datasource:
    username: root
    password: 110636
    url: jdbc:mysql://localhost:3306/jk2?serverTimezone=GMT%2B8

server:
  port: 8888

logging:
  level:
    com.mj.jk: debug

jk:
  cfg:
    cors-origins:
      - http://localhost:63342
  upload:
    base-path: F:/new_jk/
    upload-path: upload/
    image-path: img/
    video-path: video/